---
- name: check swap
  ansible.builtin.command: swapon -s
  register: swap_used_out
  changed_when: false
- name: set swap_used
  ansible.builtin.set_fact:
    swap_used: '{{ swap_used_out.stdout_lines | length > 0 }'
- name: disable swap
  become: true
  ansible.builtin.command: swapoff -a
  when: swap_used
- name: disable swap in fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: swap_used
