---
- name: Update Package Cache (apt/Ubuntu)
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Update Package Cache (dnf/CentOS)
  ansible.builtin.dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Update Package Cache (yum/Amazon)
  ansible.builtin.yum:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Amazon"
